using System.Text.Json.Serialization;

namespace HavcManager.Core.Manifest;

/// <summary>
/// The release manifest (release.json) published as an asset of every release.
/// It is the single source of truth for versions and hashes: the manager does
/// not hard-code any havc version (PHASE1_SPEC §2, §10).
/// Schema generated by installer/make_release.py (PHASE0_SPEC §6).
/// </summary>
public sealed record ReleaseManifest
{
    [JsonPropertyName("schema")] public int Schema { get; init; } = 1;
    [JsonPropertyName("channel")] public string Channel { get; init; } = "stable";
    [JsonPropertyName("app")] public string App { get; init; } = "";
    [JsonPropertyName("app_version")] public string AppVersion { get; init; } = "";
    [JsonPropertyName("published_at")] public string? PublishedAt { get; init; }
    [JsonPropertyName("requires_python")] public string? RequiresPython { get; init; }
    [JsonPropertyName("requires_env_rebuild")] public bool RequiresEnvRebuild { get; init; }
    [JsonPropertyName("bootstrap_min_version")] public string? BootstrapMinVersion { get; init; }
    [JsonPropertyName("runtime")] public RuntimeInfo? Runtime { get; init; }
    [JsonPropertyName("wheels")] public IReadOnlyList<ArtifactEntry> Wheels { get; init; } = [];
    [JsonPropertyName("assets")] public IReadOnlyList<ArtifactEntry> Assets { get; init; } = [];
    [JsonPropertyName("weights")] public IReadOnlyList<ArtifactEntry> Weights { get; init; } = [];
    [JsonPropertyName("tools")] public IReadOnlyList<ArtifactEntry> Tools { get; init; } = [];
    [JsonPropertyName("notes_url")] public string? NotesUrl { get; init; }
}
