//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly-typed access to Resources/Strings.resx.
//     Regenerated by Visual Studio when the .resx changes
//     (generator: PublicResXFileCodeGenerator — x:Static needs public members).
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavcManager.App.Resources;

/// <summary>UI strings (English — see PHASE1_SPEC §8).</summary>
public static class Strings
{
    private static readonly System.Resources.ResourceManager ResourceManager =
        new("HavcManager.App.Resources.Strings", typeof(Strings).Assembly);

    public static string AppTitle => ResourceManager.GetString("AppTitle")!;

    public static string Back => ResourceManager.GetString("Back")!;

    public static string Browse => ResourceManager.GetString("Browse")!;

    public static string Cancel => ResourceManager.GetString("Cancel")!;

    public static string Close => ResourceManager.GetString("Close")!;

    public static string ComponentsDinov2 => ResourceManager.GetString("ComponentsDinov2")!;

    public static string ComponentsServerGui => ResourceManager.GetString("ComponentsServerGui")!;

    public static string ComponentsTitle => ResourceManager.GetString("ComponentsTitle")!;

    public static string Continue => ResourceManager.GetString("Continue")!;

    public static string DesktopShortcutCheck => ResourceManager.GetString("DesktopShortcutCheck")!;

    public static string ErrorTitle => ResourceManager.GetString("ErrorTitle")!;

    public static string FinishTitle => ResourceManager.GetString("FinishTitle")!;

    public static string FinishVersionLabel => ResourceManager.GetString("FinishVersionLabel")!;

    public static string FoldersTitle => ResourceManager.GetString("FoldersTitle")!;

    public static string ForceStop => ResourceManager.GetString("ForceStop")!;

    public static string Install => ResourceManager.GetString("Install")!;

    public static string InstalledTitle => ResourceManager.GetString("InstalledTitle")!;

    public static string LabelInstallFolder => ResourceManager.GetString("LabelInstallFolder")!;

    public static string LabelModelsFolder => ResourceManager.GetString("LabelModelsFolder")!;

    public static string LogLabel => ResourceManager.GetString("LogLabel")!;

    public static string ModelsHint => ResourceManager.GetString("ModelsHint")!;

    public static string OpenFolderButton => ResourceManager.GetString("OpenFolderButton")!;

    public static string OpenGui => ResourceManager.GetString("OpenGui")!;

    public static string OpenReleaseNotes => ResourceManager.GetString("OpenReleaseNotes")!;

    public static string OpenWorkFolderButton => ResourceManager.GetString("OpenWorkFolderButton")!;

    public static string PreflightRunning => ResourceManager.GetString("PreflightRunning")!;

    public static string PreflightTitle => ResourceManager.GetString("PreflightTitle")!;

    public static string ProgressTitle => ResourceManager.GetString("ProgressTitle")!;

    public static string SetupVersionLabel => ResourceManager.GetString("SetupVersionLabel")!;

    public static string ShowLogButton => ResourceManager.GetString("ShowLogButton")!;

    public static string StartInstallation => ResourceManager.GetString("StartInstallation")!;

    public static string StartServerButton => ResourceManager.GetString("StartServerButton")!;

    public static string StatusFailed => ResourceManager.GetString("StatusFailed")!;

    public static string StatusFetchingManifest => ResourceManager.GetString("StatusFetchingManifest")!;

    public static string StatusFinishing => ResourceManager.GetString("StatusFinishing")!;

    public static string StatusPreparing => ResourceManager.GetString("StatusPreparing")!;

    public static string StatusStopped => ResourceManager.GetString("StatusStopped")!;

    public static string StatusStopping => ResourceManager.GetString("StatusStopping")!;

    public static string SummaryFilesLabel => ResourceManager.GetString("SummaryFilesLabel")!;

    public static string SummaryTitle => ResourceManager.GetString("SummaryTitle")!;

    public static string SummaryVersionLabel => ResourceManager.GetString("SummaryVersionLabel")!;

    public static string UninstallButton => ResourceManager.GetString("UninstallButton")!;

    public static string UninstallConfirmButton => ResourceManager.GetString("UninstallConfirmButton")!;

    public static string UninstallDeleteModelsCheck => ResourceManager.GetString("UninstallDeleteModelsCheck")!;

    public static string UninstallDialogText => ResourceManager.GetString("UninstallDialogText")!;

    public static string UninstallDialogTitle => ResourceManager.GetString("UninstallDialogTitle")!;

    public static string UninstallDoneMessage => ResourceManager.GetString("UninstallDoneMessage")!;

    public static string UninstallPartialMessage => ResourceManager.GetString("UninstallPartialMessage")!;

    public static string UnexpectedErrorTitle => ResourceManager.GetString("UnexpectedErrorTitle")!;

    public static string AboutLine => ResourceManager.GetString("AboutLine")!;

    public static string CheckForUpdatesButton => ResourceManager.GetString("CheckForUpdatesButton")!;

    public static string DirtyWarning => ResourceManager.GetString("DirtyWarning")!;

    public static string FreeSpaceFormat => ResourceManager.GetString("FreeSpaceFormat")!;

    public static string LastVerifyFailedFormat => ResourceManager.GetString("LastVerifyFailedFormat")!;

    public static string LastVerifyNever => ResourceManager.GetString("LastVerifyNever")!;

    public static string LastVerifyOkFormat => ResourceManager.GetString("LastVerifyOkFormat")!;

    public static string LockDialogText => ResourceManager.GetString("LockDialogText")!;

    public static string LockDialogTitle => ResourceManager.GetString("LockDialogTitle")!;

    public static string NoButton => ResourceManager.GetString("NoButton")!;

    public static string NoInstallationMessage => ResourceManager.GetString("NoInstallationMessage")!;

    public static string ProjectLinkText => ResourceManager.GetString("ProjectLinkText")!;

    public static string RebuildRequiredMessage => ResourceManager.GetString("RebuildRequiredMessage")!;

    public static string RepairButton => ResourceManager.GetString("RepairButton")!;

    public static string RepairCompleteMessage => ResourceManager.GetString("RepairCompleteMessage")!;

    public static string RepairNoWheelMessage => ResourceManager.GetString("RepairNoWheelMessage")!;

    public static string RetryButton => ResourceManager.GetString("RetryButton")!;

    public static string StatusCheckingUpdates => ResourceManager.GetString("StatusCheckingUpdates")!;

    public static string StatusRollingBack => ResourceManager.GetString("StatusRollingBack")!;

    public static string TerminateButton => ResourceManager.GetString("TerminateButton")!;

    public static string UpToDateMessage => ResourceManager.GetString("UpToDateMessage")!;

    public static string UpdateAvailableMessage => ResourceManager.GetString("UpdateAvailableMessage")!;

    public static string UpdateAvailableTitle => ResourceManager.GetString("UpdateAvailableTitle")!;

    public static string UpdateCompleteMessage => ResourceManager.GetString("UpdateCompleteMessage")!;

    public static string UpdateDirtyMessage => ResourceManager.GetString("UpdateDirtyMessage")!;

    public static string UpdateRolledBackMessage => ResourceManager.GetString("UpdateRolledBackMessage")!;

    public static string YesButton => ResourceManager.GetString("YesButton")!;

    public static string WelcomeSubtitle => ResourceManager.GetString("WelcomeSubtitle")!;

    public static string WelcomeTitle => ResourceManager.GetString("WelcomeTitle")!;
}
