//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly-typed access to Resources/Strings.resx.
//     Regenerated by Visual Studio when the .resx changes
//     (generator: PublicResXFileCodeGenerator — x:Static needs public members).
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavcManager.App.Resources;

/// <summary>UI strings (English — see PHASE1_SPEC §8).</summary>
public static class Strings
{
    private static readonly System.Resources.ResourceManager ResourceManager =
        new("HavcManager.App.Resources.Strings", typeof(Strings).Assembly);

    public static string AppTitle => ResourceManager.GetString("AppTitle")!;

    public static string WelcomeTitle => ResourceManager.GetString("WelcomeTitle")!;

    public static string WelcomeSubtitle => ResourceManager.GetString("WelcomeSubtitle")!;

    public static string StartInstallation => ResourceManager.GetString("StartInstallation")!;

    public static string NotImplementedYet => ResourceManager.GetString("NotImplementedYet")!;
}
